### PR TITLE
Prototype for TreeMap

### PR DESCRIPTION
**Pull request by szabopeter**
The goal of this PR is to clarify the interface for the proposed TreeMap and provide a minimal implementation that fulfills the functional requirements. This implementation does not aim to be efficient.

Addresses issue #2

### CODE REVIEW

**Comment by fukatani** [comment]
Thank you for your PR!
In terms of interface, looks almost perfect to me.
If anything, I want `.values()`.

**Comment by fukatani** [comment]
And could you add description on readme.md about `TreeMap`?

**Comment by szabopeter** [comment]
Thanks for the feedback!
- values() returns items sorted by keys now
- Readme is updated (and TreeMap got a docstring now)
+ I noticed that using clear lead to an exception, so I fixed that too

**Comment by fukatani** [comment]
LGTM! Thanks!

**Pull request merged**
